Documentation:
  Enabled: false

Layout/LineLength:
  Max: 99

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassVars:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  ExcludedMethods: [main_menu]
